baseURL = 'https://tejas-kale.github.io/blog/'
languageCode = 'en-us'
title = 'Tejas Kale'
theme = 'paper'

# Cache configuration for GitHub Pages
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menus]
    [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 10

    [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20